spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: boot
    password: boot
    virtual-host: /boot-ems
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: auto
      simple:
        acknowledge-mode: auto

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#下面Spring的配置文件基本就不用修改了
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#配置在boot启动时运行sql脚本
    initialization-mode: always
    schema: classpath:schema.sql

mybatis:
  typeAliasesPackage: com.org.peysen.bootrabbitmq.entity
  mapper-locations: classpath:mappers/*Mapper.xml

logging:
  level:
    com.org.peysen.bootrabbitmq.mapper: trace

