# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        min-idle: 0
