--建表sql
CREATE TABLE IF NOT EXISTS FAULT_CODE_CONFIG(
          FC_ID             VARCHAR(30) PRIMARY KEY ,
          FC_DESC           VARCHAR(64)  NOT NULL ,
          FAULT_TYPE        VARCHAR(64)  NOT NULL ,
          SERVICE_NAME      VARCHAR(64)  NOT NULL ,
          SCAN_FILE_NAME    VARCHAR(64)  NOT NULL ,
          KEY_WORD          VARCHAR(64)  NOT NULL ,
          DUTY              VARCHAR(64)  NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

