server:
  port: 8080
  servlet:
    context-path: /sharding-jdbc
spring:
  application:
    name: sharding-jdbc
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    enabled: true
    datasource:
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&useSSL=true
        username: root
        password: root
    sharding:
      tables:
        t_order:
          keyGenerator:
            type: SNOWFLAKE
            column: order_id
          actualDataNodes: m1.t_order_$->{1..2}
          tableStrategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 2 + 1}
    props:
      sql:
        show: true
logging:
  level:
    root: info
